export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import About from '@/components/About'
import SignUp from '@/components/SignUp'
import './global.css'
import Nav from "@/components/nav"
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
        <Nav/>
        {children}
        <About/>
        <SignUp/>
        </body>
    </html>
  )
}
