
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import About from '@/components/About'
import SignUp from '@/components/SignUp'
import ContactForm from '@/components/ContactForm'
import './global.css'    
import Nav from "@/components/nav"
import Socials from '@/components/Socials'
import Footer from '@/components/Footer'
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
        <body>
          <Nav/>
          {children}
          <Footer/>
        </body> 
      
      
    </html>
  )
}
